version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: syndic_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2004
      POSTGRES_DB: syndic
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
